### ISSUE TITLE
Course

### ISSUE THREAD

**Issue by pooriyaadibrad** [HHHMHA/django-roadmap#6]
Hi thanks for this roadmap 
Can introduce me course match this road map ?

**Comment by HHHMHA** [comment]
Unfortunately, there is no single course that will walk you through all these topics.
I'll try to share some resources that together can work for you later @pooriyaadibrad

**Comment by pooriyaadibrad** [comment]
Thanks for that and I try use to improve my skill 😉

**Comment by HHHMHA** [comment]
np sorry for the delay I will share tommorow

**Comment by pooriyaadibrad** [comment]
No problem bro it's ok😉

**Comment by HHHMHA** [comment]
for virtual envs I recommend learning https://github.com/astral-sh/uv from the docs
if you don't know what python virtual envs are you can check this:
https://csguide.cs.princeton.edu/software/virtualenv#:~:text=In%20a%20nutshell%2C%20Python%20virtual,or%20used%20by%20other%20projects.

if your python skills are good you can read this book:
Effective Python Book

if not first I recommend learning basic python:
https://www.youtube.com/watch?v=QXeEoD0pB3E&list=PLsyeobzWxl7poL9JTVyndKe62ieoN-MZ3

for version control I recommend git best resource is practice really but you can use:
https://www.youtube.com/playlist?list=PL_euSNU_eLbegnt7aR8I1gXfLhKZbxnYX

Important note:
you need to learn basic commands from terminal
but after that it's ok to use any graphical interface. Personally I use the integrated one that comes with PyCharm.

IDE: I recommend PyCharm it's by far the best but if you can't afford it you can go with vs code
be sure to learn advanced tricks with the ide can really help you like global search, bulk replace, VCS integrated, snippets, Local History, shortcuts, ...etc

for networks:
https://www.youtube.com/playlist?list=PLkW9FMxqUvyZaSQNQslneeODER3bJCb2K
you can skip a lot of that course but knowing all of it will make you better

ssh:
https://www.youtube.com/watch?v=v45p_kJV9i4
https://www.youtube.com/watch?v=pWDHUlvcAsg
https://www.youtube.com/watch?v=SXg-dFYP9KA

I personnaly use termuis

I recommend this as a terminal:
https://www.warp.dev/

for databaseas watch any youtube course but better to learn a couple not just one: PostgreSQL and MySQL for example
for software engineering you need to research and apply each topic
but I can recommend some books that really helps too:
Agile Software Development Principles, Patterns, and Practices
Clean Code A Handbook of Agile Software Craftsmanship
System Design Interview An Insider’s Guide

After you finish these you can start learning django from the resources provided
and while learning django you can start learning other topics at the same time (docker, sentry, Elastic Stack, Hosting)

**Comment by pooriyaadibrad** [comment]
Tkaks bro this valuable for me 😉❤️
